services:
  - type: web
    runtime: python
    name: tonforge-web
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    # Миграции перед запуском приложения (preDeploy недоступен на Free)
    startCommand: bash -lc "python -m database.migrate && uvicorn webview.backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: DATABASE_URL
        fromDatabase:
          name: tonforge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: tonforge-kv
          property: connectionString
      - key: TON_API_KEY
        sync: false
      - key: OTHER_SECRET
        sync: false

  - type: worker
    runtime: python
    name: tonforge-worker
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tonforge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: tonforge-kv
          property: connectionString
      - key: TON_API_KEY
        sync: false
      - key: OTHER_SECRET
        sync: false

  - type: keyvalue
    name: tonforge-kv
    plan: free
    ipAllowList: []                 # только внутренние подключения Render
    maxmemoryPolicy: noeviction

databases:
  - name: tonforge-db
    plan: free