services:
  - type: web
    name: tonforge-web
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn webview.backend.main:app --host 0.0.0.0 --port $PORT
preDeployCommand: python -m database.migrate
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: TON_API_KEY
        value: ${TON_API_KEY}
      - key: OTHER_SECRET
        value: ${OTHER_SECRET}
  - type: worker
    name: tonforge-worker
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: TON_API_KEY
        value: ${TON_API_KEY}
      - key: OTHER_SECRET
        value: ${OTHER_SECRET}
