services:
  - type: web
    name: tonforge-web
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python -m database.migrate
    startCommand: uvicorn webview.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TON_API_KEY
        sync: false
      - key: TON_WALLET
        sync: false
      - key: BASE_WEBAPP_URL
        sync: false

  - type: worker
    name: tonforge-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m main
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ENABLE_SCHEDULER
        value: "0"
      - key: TONAPI_KEY
        sync: false
      - key: TON_RECEIVER_WALLET
        sync: false

cronJobs:
  - name: daily-accruals
    schedule: "0 1 * * *"  # ежедневно 01:00 UTC
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m jobs.accrualse: tonforge-kv
    plan: free
    ipAllowList: []                 # только внутренние подключения Render
    maxmemoryPolicy: noeviction

databases:
  - name: tonforge-db
    plan: free