services:
  - type: web
    name: tonforge-web
    runtime: python
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python -m database.migrate
    startCommand: uvicorn webview.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BASE_WEBAPP_URL
        value: https://tonforge-web.onrender.com
      - key: TON_API_KEY
        sync: false
      - key: TON_WALLET
        sync: false
      - key: REDIS_URL
        sync: false

  - type: worker
    name: tonforge-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m main
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TON_API_KEY
        sync: false
      - key: TON_WALLET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ENABLE_SCHEDULER
        value: "0"

  # Cron-джоба — это ТОЖЕ сервис (type: cron), не корневой cronJobs:
  - type: cron
    name: daily-accruals
    runtime: python
    schedule: "0 1 * * *"               # ежедневно 01:00 UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python -m jobs.accruals

  # Redis/KeyValue объявляется как отдельный сервис типа keyvalue
  - type: keyvalue
    name: tonforge-kv
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []                      # доступ только изнутри Render

databases:
  - name: tonforge-db
    plan: free